version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    network_mode: bridge
    volumes:
      - /apps/nginx/conf:/etc/nginx/conf.d
      - /apps/nginx/vhost:/etc/nginx/vhost.d
      - /apps/nginx/html:/usr/share/nginx/html
      - /apps/nginx/dhparam:/etc/nginx/dhparam
      - /apps/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - PUID=998
      - PGID=998
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    network_mode: bridge
    volumes_from:
      - nginx-proxy
    volumes:
      - /apps/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=ssl@shuffman.com
      - PUID=998
      - PGID=998

  jenkins-c:
    container_name: jenkins-c
    image: jenkins/jenkins:lts
    volumes:
      - '/apps/jenkins_home:/var/jenkins_home'
    ports:
      - "8080"
    environment:
      - PUID=998
      - PGID=998

  nginx:
    container_name: jenkins-nginx
    image: nginx
    links:
      - jenkins-c
    volumes:
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
    environment:
      - VIRTUAL_HOST=jenkins.shuffman.dev
      - LETSENCRYPT_HOST=jenkins.shuffman.dev
      - PUID=998
      - PGID=998
